# STAGE 1: Build React app using Node.js
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Creates optimized /dist folder
RUN npm run build

# STAGE 2: Serve built files with Nginx
# Node.js NOT included here = much smaller image
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]